function  [ceq] = general_coupled_linear(p, A, b, At, bt)
% function  [ceq] = general_coupled_linear(p, A, b, At, bt)
% Purpose : coupled linear order condition for ARK SSP IMEX  method

[ceq, wgt] = tall_tree(p, A, At);
e = ones(size(b));

exp = arrayfun(@(i) b'*ceq{i}*e - wgt(i), 1:numel(ceq))';
imp = arrayfun(@(i) bt'*ceq{i}*e - wgt(i), 1:numel(ceq))';

ceq = [exp(:); imp(:)];

end

function [ceq, wgt] = tall_tree(p, A, At)
ceq = {eye(size(A))};
wgt = [1];

if p >= 2
    ceq(end+1) = {A};
    ceq(end+1) = {At};
    wgt = [wgt; 0.5*ones(2,1)];
end

if p >= 3
    ceq(end+1) = {A*A};
    ceq(end+1) = {A*At};
    ceq(end+1) = {At*A};
    ceq(end+1) = {At*At};
    wgt = [wgt; 1/factorial(3)*ones(2^(3-1),1)];
end

if p >= 4
    ceq(end+1) = {A*A*A};
    ceq(end+1) = {A*A*At};
    ceq(end+1) = {A*At*A};
    ceq(end+1) = {A*At*At};
    ceq(end+1) = {At*A*A};
    ceq(end+1) = {At*A*At};
    ceq(end+1) = {At*At*A};
    ceq(end+1) = {At*At*At};
    wgt = [wgt; 1/factorial(4)*ones(2^(4-1),1)];
end

if p >= 5
    ceq(end+1) = {A*A*A*A};
    ceq(end+1) = {A*A*A*At};
    ceq(end+1) = {A*A*At*A};
    ceq(end+1) = {A*A*At*At};
    ceq(end+1) = {A*At*A*A};
    ceq(end+1) = {A*At*A*At};
    ceq(end+1) = {A*At*At*A};
    ceq(end+1) = {A*At*At*At};
    ceq(end+1) = {At*A*A*A};
    ceq(end+1) = {At*A*A*At};
    ceq(end+1) = {At*A*At*A};
    ceq(end+1) = {At*A*At*At};
    ceq(end+1) = {At*At*A*A};
    ceq(end+1) = {At*At*A*At};
    ceq(end+1) = {At*At*At*A};
    ceq(end+1) = {At*At*At*At};
    wgt = [wgt; 1/factorial(5)*ones(2^(5-1),1)];
end

if p >= 6
    ceq(end+1) = {A*A*A*A*A};
    ceq(end+1) = {A*A*A*A*At};
    ceq(end+1) = {A*A*A*At*A};
    ceq(end+1) = {A*A*A*At*At};
    ceq(end+1) = {A*A*At*A*A};
    ceq(end+1) = {A*A*At*A*At};
    ceq(end+1) = {A*A*At*At*A};
    ceq(end+1) = {A*A*At*At*At};
    ceq(end+1) = {A*At*A*A*A};
    ceq(end+1) = {A*At*A*A*At};
    ceq(end+1) = {A*At*A*At*A};
    ceq(end+1) = {A*At*A*At*At};
    ceq(end+1) = {A*At*At*A*A};
    ceq(end+1) = {A*At*At*A*At};
    ceq(end+1) = {A*At*At*At*A};
    ceq(end+1) = {A*At*At*At*At};
    ceq(end+1) = {At*A*A*A*A};
    ceq(end+1) = {At*A*A*A*At};
    ceq(end+1) = {At*A*A*At*A};
    ceq(end+1) = {At*A*A*At*At};
    ceq(end+1) = {At*A*At*A*A};
    ceq(end+1) = {At*A*At*A*At};
    ceq(end+1) = {At*A*At*At*A};
    ceq(end+1) = {At*A*At*At*At};
    ceq(end+1) = {At*At*A*A*A};
    ceq(end+1) = {At*At*A*A*At};
    ceq(end+1) = {At*At*A*At*A};
    ceq(end+1) = {At*At*A*At*At};
    ceq(end+1) = {At*At*At*A*A};
    ceq(end+1) = {At*At*At*A*At};
    ceq(end+1) = {At*At*At*At*A};
    ceq(end+1) = {At*At*At*At*At};
    wgt = [wgt; 1/factorial(6)*ones(2^(6-1),1)];
end


if p >= 7
    ceq(end+1) = {A*A*A*A*A*A};
    ceq(end+1) = {A*A*A*A*A*At};
    ceq(end+1) = {A*A*A*A*At*A};
    ceq(end+1) = {A*A*A*A*At*At};
    ceq(end+1) = {A*A*A*At*A*A};
    ceq(end+1) = {A*A*A*At*A*At};
    ceq(end+1) = {A*A*A*At*At*A};
    ceq(end+1) = {A*A*A*At*At*At};
    ceq(end+1) = {A*A*At*A*A*A};
    ceq(end+1) = {A*A*At*A*A*At};
    ceq(end+1) = {A*A*At*A*At*A};
    ceq(end+1) = {A*A*At*A*At*At};
    ceq(end+1) = {A*A*At*At*A*A};
    ceq(end+1) = {A*A*At*At*A*At};
    ceq(end+1) = {A*A*At*At*At*A};
    ceq(end+1) = {A*A*At*At*At*At};
    ceq(end+1) = {A*At*A*A*A*A};
    ceq(end+1) = {A*At*A*A*A*At};
    ceq(end+1) = {A*At*A*A*At*A};
    ceq(end+1) = {A*At*A*A*At*At};
    ceq(end+1) = {A*At*A*At*A*A};
    ceq(end+1) = {A*At*A*At*A*At};
    ceq(end+1) = {A*At*A*At*At*A};
    ceq(end+1) = {A*At*A*At*At*At};
    ceq(end+1) = {A*At*At*A*A*A};
    ceq(end+1) = {A*At*At*A*A*At};
    ceq(end+1) = {A*At*At*A*At*At};
    ceq(end+1) = {A*At*At*A*At*At};
    ceq(end+1) = {A*At*At*At*A*A};
    ceq(end+1) = {A*At*At*At*A*At};
    ceq(end+1) = {A*At*At*At*At*A};
    ceq(end+1) = {A*At*At*At*At*At};
    ceq(end+1) = {At*A*A*A*A*A};
    ceq(end+1) = {At*A*A*A*A*At};
    ceq(end+1) = {At*A*A*A*At*A};
    ceq(end+1) = {At*A*A*A*At*At};
    ceq(end+1) = {At*A*A*At*A*A};
    ceq(end+1) = {At*A*A*At*A*At};
    ceq(end+1) = {At*A*A*At*At*A};
    ceq(end+1) = {At*A*A*At*At*At};
    ceq(end+1) = {At*A*At*A*A*A};
    ceq(end+1) = {At*A*At*A*A*At};
    ceq(end+1) = {At*A*At*A*At*A};
    ceq(end+1) = {At*A*At*A*At*At};
    ceq(end+1) = {At*A*At*At*A*A};
    ceq(end+1) = {At*A*At*At*A*At};
    ceq(end+1) = {At*A*At*At*At*A};
    ceq(end+1) = {At*A*At*At*At*At};
    ceq(end+1) = {At*At*A*A*A*A};
    ceq(end+1) = {At*At*A*A*A*At};
    ceq(end+1) = {At*At*A*A*At*A};
    ceq(end+1) = {At*At*A*A*At*At};
    ceq(end+1) = {At*At*A*At*A*A};
    ceq(end+1) = {At*At*A*At*A*At};
    ceq(end+1) = {At*At*A*At*At*A};
    ceq(end+1) = {At*At*A*At*At*At};
    ceq(end+1) = {At*At*At*A*A*A};
    ceq(end+1) = {At*At*At*A*A*At};
    ceq(end+1) = {At*At*At*A*At*A};
    ceq(end+1) = {At*At*At*A*At*At};
    ceq(end+1) = {At*At*At*At*A*A};
    ceq(end+1) = {At*At*At*At*A*At};
    ceq(end+1) = {At*At*At*At*At*A};
    ceq(end+1) = {At*At*At*At*At*At};
    wgt = [wgt; 1/factorial(7)*ones(2^(7-1),1)];
end

if p >= 8
    ceq(end+1) = {A*A*A*A*A*A*A};
    ceq(end+1) = {A*A*A*A*A*A*At};
    ceq(end+1) = {A*A*A*A*A*At*A};
    ceq(end+1) = {A*A*A*A*A*At*At};
    ceq(end+1) = {A*A*A*A*At*A*A};
    ceq(end+1) = {A*A*A*A*At*A*At};
    ceq(end+1) = {A*A*A*A*At*At*A};
    ceq(end+1) = {A*A*A*A*At*At*At};
    ceq(end+1) = {A*A*A*At*A*A*A};
    ceq(end+1) = {A*A*A*At*A*A*At};
    ceq(end+1) = {A*A*A*At*A*At*A};
    ceq(end+1) = {A*A*A*At*A*At*At};
    ceq(end+1) = {A*A*A*At*At*A*A};
    ceq(end+1) = {A*A*A*At*At*A*At};
    ceq(end+1) = {A*A*A*At*At*At*A};
    ceq(end+1) = {A*A*A*At*At*At*At};
    ceq(end+1) = {A*A*At*A*A*A*A};
    ceq(end+1) = {A*A*At*A*A*A*At};
    ceq(end+1) = {A*A*At*A*A*At*A};
    ceq(end+1) = {A*A*At*A*A*At*At};
    ceq(end+1) = {A*A*At*A*At*A*A};
    ceq(end+1) = {A*A*At*A*At*A*At};
    ceq(end+1) = {A*A*At*A*At*At*A};
    ceq(end+1) = {A*A*At*A*At*At*At};
    ceq(end+1) = {A*A*At*At*A*A*A};
    ceq(end+1) = {A*A*At*At*A*A*At};
    ceq(end+1) = {A*A*At*At*A*At*A};
    ceq(end+1) = {A*A*At*At*A*At*At};
    ceq(end+1) = {A*A*At*At*At*A*A};
    ceq(end+1) = {A*A*At*At*At*A*At};
    ceq(end+1) = {A*A*At*At*At*At*A};
    ceq(end+1) = {A*A*At*At*At*At*At};
    ceq(end+1) = {A*At*A*A*A*A*A};
    ceq(end+1) = {A*At*A*A*A*A*At};
    ceq(end+1) = {A*At*A*A*A*At*A};
    ceq(end+1) = {A*At*A*A*A*At*At};
    ceq(end+1) = {A*At*A*A*At*A*A};
    ceq(end+1) = {A*At*A*A*At*A*At};
    ceq(end+1) = {A*At*A*A*At*At*A};
    ceq(end+1) = {A*At*A*A*At*At*At};
    ceq(end+1) = {A*At*A*At*A*A*A};
    ceq(end+1) = {A*At*A*At*A*A*At};
    ceq(end+1) = {A*At*A*At*A*At*A};
    ceq(end+1) = {A*At*A*At*A*At*At};
    ceq(end+1) = {A*At*A*At*At*A*A};
    ceq(end+1) = {A*At*A*At*At*A*At};
    ceq(end+1) = {A*At*A*At*At*At*A};
    ceq(end+1) = {A*At*A*At*At*At*At};
    ceq(end+1) = {A*At*At*A*A*A*A};
    ceq(end+1) = {A*At*At*A*A*A*At};
    ceq(end+1) = {A*At*At*A*A*At*A};
    ceq(end+1) = {A*At*At*A*A*At*At};
    ceq(end+1) = {A*At*At*A*At*At*A};
    ceq(end+1) = {A*At*At*A*At*At*At};
    ceq(end+1) = {A*At*At*A*At*At*A};
    ceq(end+1) = {A*At*At*A*At*At*At};
    ceq(end+1) = {A*At*At*At*A*A*A};
    ceq(end+1) = {A*At*At*At*A*A*At};
    ceq(end+1) = {A*At*At*At*A*At*A};
    ceq(end+1) = {A*At*At*At*A*At*At};
    ceq(end+1) = {A*At*At*At*At*A*A};
    ceq(end+1) = {A*At*At*At*At*A*At};
    ceq(end+1) = {A*At*At*At*At*At*A};
    ceq(end+1) = {A*At*At*At*At*At*At};
    ceq(end+1) = {At*A*A*A*A*A*A};
    ceq(end+1) = {At*A*A*A*A*A*At};
    ceq(end+1) = {At*A*A*A*A*At*A};
    ceq(end+1) = {At*A*A*A*A*At*At};
    ceq(end+1) = {At*A*A*A*At*A*A};
    ceq(end+1) = {At*A*A*A*At*A*At};
    ceq(end+1) = {At*A*A*A*At*At*A};
    ceq(end+1) = {At*A*A*A*At*At*At};
    ceq(end+1) = {At*A*A*At*A*A*A};
    ceq(end+1) = {At*A*A*At*A*A*At};
    ceq(end+1) = {At*A*A*At*A*At*A};
    ceq(end+1) = {At*A*A*At*A*At*At};
    ceq(end+1) = {At*A*A*At*At*A*A};
    ceq(end+1) = {At*A*A*At*At*A*At};
    ceq(end+1) = {At*A*A*At*At*At*A};
    ceq(end+1) = {At*A*A*At*At*At*At};
    ceq(end+1) = {At*A*At*A*A*A*A};
    ceq(end+1) = {At*A*At*A*A*A*At};
    ceq(end+1) = {At*A*At*A*A*At*A};
    ceq(end+1) = {At*A*At*A*A*At*At};
    ceq(end+1) = {At*A*At*A*At*A*A};
    ceq(end+1) = {At*A*At*A*At*A*At};
    ceq(end+1) = {At*A*At*A*At*At*A};
    ceq(end+1) = {At*A*At*A*At*At*At};
    ceq(end+1) = {At*A*At*At*A*A*A};
    ceq(end+1) = {At*A*At*At*A*A*At};
    ceq(end+1) = {At*A*At*At*A*At*A};
    ceq(end+1) = {At*A*At*At*A*At*At};
    ceq(end+1) = {At*A*At*At*At*A*A};
    ceq(end+1) = {At*A*At*At*At*A*At};
    ceq(end+1) = {At*A*At*At*At*At*A};
    ceq(end+1) = {At*A*At*At*At*At*At};
    ceq(end+1) = {At*At*A*A*A*A*A};
    ceq(end+1) = {At*At*A*A*A*A*At};
    ceq(end+1) = {At*At*A*A*A*At*A};
    ceq(end+1) = {At*At*A*A*A*At*At};
    ceq(end+1) = {At*At*A*A*At*A*A};
    ceq(end+1) = {At*At*A*A*At*A*At};
    ceq(end+1) = {At*At*A*A*At*At*A};
    ceq(end+1) = {At*At*A*A*At*At*At};
    ceq(end+1) = {At*At*A*At*A*A*A};
    ceq(end+1) = {At*At*A*At*A*A*At};
    ceq(end+1) = {At*At*A*At*A*At*A};
    ceq(end+1) = {At*At*A*At*A*At*At};
    ceq(end+1) = {At*At*A*At*At*A*A};
    ceq(end+1) = {At*At*A*At*At*A*At};
    ceq(end+1) = {At*At*A*At*At*At*A};
    ceq(end+1) = {At*At*A*At*At*At*At};
    ceq(end+1) = {At*At*At*A*A*A*A};
    ceq(end+1) = {At*At*At*A*A*A*At};
    ceq(end+1) = {At*At*At*A*A*At*A};
    ceq(end+1) = {At*At*At*A*A*At*At};
    ceq(end+1) = {At*At*At*A*At*A*A};
    ceq(end+1) = {At*At*At*A*At*A*At};
    ceq(end+1) = {At*At*At*A*At*At*A};
    ceq(end+1) = {At*At*At*A*At*At*At};
    ceq(end+1) = {At*At*At*At*A*A*A};
    ceq(end+1) = {At*At*At*At*A*A*At};
    ceq(end+1) = {At*At*At*At*A*At*A};
    ceq(end+1) = {At*At*At*At*A*At*At};
    ceq(end+1) = {At*At*At*At*At*A*A};
    ceq(end+1) = {At*At*At*At*At*A*At};
    ceq(end+1) = {At*At*At*At*At*At*A};
    ceq(end+1) = {At*At*At*At*At*At*At};
    wgt = [wgt; 1/factorial(8)*ones(2^(8-1),1)];
end

end
